repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.281
    hooks:
        - id: ruff
    args: [ --fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--safe]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing