version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dev.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    command: uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage
